CMD_INSCRIPTION = 0
CMD_CONNECTION = 1
CMD_GET_SCORES = 2
CMD_GET_MAPS = 3
CMD_GET_GAMES = 4
CMD_CREATE_GAME = 5
CMD_JOIN_GAME = 6
CMD_GET_GAME = 7
CMD_LEAVE_GAME = 8
CMD_EDIT_GAME = 9
CMD_STOCK_SOCK_GAME = 10
CMD_LAUNCH_GAME = 11

CMD_OK = 100
CMD_NOT_OK = 101
